import * as stylex from "@stylexjs/stylex";

// A constant can be used to avoid repeating the media query
const DARK = "@media (prefers-color-scheme: dark)";

export const colors = stylex.defineVars({
  // indigo
  accent1: { default: "#FDFDFE" },
  accent2: { default: "#F7F9FF" },
  accent3: { default: "#EDF2FE" },
  accent4: { default: "#E1E9FF" },
  accent5: { default: "#D2DEFF" },
  accent6: { default: "#C1D0FF" },
  accent7: { default: "#ABBDF9" },
  accent8: { default: "#8DA4EF" },
  accent9: { default: "#3E63DD" },
  accent10: { default: "#3358D4" },
  accent11: { default: "#3A5BC7" },
  accent12: { default: "#1F2D5C" },
  // slate
  grey1: { default: "#FCFCFD" },
  grey2: { default: "#F9F9FB" },
  grey3: { default: "#F0F0F3" },
  grey4: { default: "#E8E8EC" },
  grey5: { default: "#E0E1E6" },
  grey6: { default: "#D9D9E0" },
  grey7: { default: "#CDCED6" },
  grey8: { default: "#B9BBC6" },
  grey9: { default: "#8B8D98" },
  grey10: { default: "#80838D" },
  grey11: { default: "#60646C" },
  grey12: { default: "#1C2024" },
  // ruby
  errors1: { default: "#FFFCFD" },
  errors2: { default: "#FFF7F8" },
  errors3: { default: "#FEEAED" },
  errors4: { default: "#FFDCE1" },
  errors5: { default: "#FFCED6" },
  errors6: { default: "#F8BFC8" },
  errors7: { default: "#EFACB8" },
  errors8: { default: "#E592A3" },
  errors9: { default: "#E54666" },
  errors10: { default: "#DC3B5D" },
  errors11: { default: "#CA244D" },
  errors12: { default: "#64172B" },
  // jade
  success1: { default: "#FBFEFD" },
  success2: { default: "#F4FBF7" },
  success3: { default: "#E6F7ED" },
  success4: { default: "#D6F1E3" },
  success5: { default: "#C3E9D7" },
  success6: { default: "#ACDEC8" },
  success7: { default: "#8BCEB6" },
  success8: { default: "#56BA9F" },
  success9: { default: "#29A383" },
  success10: { default: "#26997B" },
  success11: { default: "#208368" },
  success12: { default: "#1D3B31" },
  // amber
  warning1: { default: "#FEFDFB" },
  warning2: { default: "#FEFBE9" },
  warning3: { default: "#FFF7C2" },
  warning4: { default: "#FFEE9C" },
  warning5: { default: "#FBE577" },
  warning6: { default: "#F3D673" },
  warning7: { default: "#E9C162" },
  warning8: { default: "#E2A336" },
  warning9: { default: "#FFC53D" },
  warning10: { default: "#FFBA18" },
  warning11: { default: "#AB6400" },
  warning12: { default: "#4F3422" },
  // info
  info1: { default: "#FAFDFE" },
  info2: { default: "#F2FAFB" },
  info3: { default: "#DEF7F9" },
  info4: { default: "#CAF1F6" },
  info5: { default: "#B5E9F0" },
  info6: { default: "#9DDDE7" },
  info7: { default: "#7DCEDC" },
  info8: { default: "#3DB9CF" },
  info9: { default: "#00A2C7" },
  info10: { default: "#0797B9" },
  info11: { default: "#107D98" },
  info12: { default: "#0D3C48" },
});
