name: Deploy

on:
  push:
    branches:
      - main

jobs:
  push-image-dockerhub:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/home/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/home:latest

  Deploy:
    needs: push-image-dockerhub

    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/id_rsa
          echo "${{ secrets.PROD_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PROD_IP }} >> ~/.ssh/known_hosts

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files
        run: |
          scp docker-compose.yml root@${{ secrets.PROD_IP }}:/home/docker-compose.yml
          scp docker-compose.prod.yml root@${{ secrets.PROD_IP }}:/home/docker-compose.override.yml
          scp nginx.conf root@${{ secrets.PROD_IP }}:/home

      - name: Connect SSH and Update containers
        run: |
          ssh root@${{ secrets.PROD_IP }}
          ls -al
          cd /
          ls -al
          cd home
          ls -al
          cd /home
          ls -al
          docker compose down
          docker compose pull
          docker compose up -d
