name: Deploy

on:
  push:
    branches:
      - main

jobs:
  push-image-dockerhub:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: apps/home/Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/home:latest

      # - name: Build Docker image
      #   run: |
      #     docker build -t home:latest -f apps/home/Dockerfile .

      # - name: Tag and Push Docker image to Docker Hub
      #   run: |
      #     docker tag home:latest ${{ secrets.DOCKER_USERNAME }}/home:latest
      #     docker push ${{ secrets.DOCKER_USERNAME }}/home:latest

  test-ssh:
    # needs: push-image-dockerhub

    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/id_rsa
          echo "${{ secrets.PROD_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.PROD_IP }} >> ~/.ssh/known_hosts

      - name: Debug SSH Setup
        run: |
          ls -al ~/.ssh
          cat ~/.ssh/id_rsa

      - name: Test SSH Connection
        run: |
          ssh -vvv -o StrictHostKeyChecking=no root@${{ secrets.PROD_IP }} "echo SSH connection successful"

      - name: Connect SSH
        run: |
          ssh root@${{ secrets.PROD_IP }}
          touch test
          echo "hello world" > ./test
          cat test
