name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t home:latest -f apps/home/Dockerfile .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag and Push Docker image to Docker Hub
        run: |
          docker tag home:latest ${{ secrets.DOCKER_USERNAME }}/home:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/home:latest

  deploy:
    name: Deploy to DigitalOcean
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}

      - name: Copy Docker Compose file to VM
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          source: "docker-compose.yml"
          target: "~"

      - name: Deploy Docker Compose on VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd ~
            docker-compose pull
            docker-compose up -d

    # steps:
    #   - name: Set up SSH Key
    #     run: |
    #       mkdir -p ~/.ssh
    #       echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_rsa
    #       chmod 600 ~/.ssh/id_rsa

    #   - name: Deploy Docker Image
    #     run: |
    #       ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
    #         docker pull ${{ secrets.DOCKER_USERNAME }}/home:latest
    #         cd /home/github-action-deploy/myapp
    #         docker-compose up -d
    #       EOF
